title: Machine Vision and Pattern Recognition (MVPR) Research Group, East China University of Science and Technology
page-top-title: Machine Vision and Pattern Recognition (MVPR) Research Group
top-section-bg-text: Be what you wanna be
# home-subtitle: 
copyright-text: '&copy; MVPR Research Group 2026. All Rights Reserved.'
